const translations = {
    es: {
        // Navbar & Mobile Menu
        "nav_programa": "Programa del evento",
        "nav_prog_title": "Agenda completa",
        "nav_prog_desc": "Descubre todas las charlas y talleres del ToB.",
        "nav_speakers": "Speakers",
        "nav_speak_title": "Nuestros Ponentes",
        "nav_speak_desc": "Conoce a los expertos que liderarán el evento.",
        "nav_sponsors": "Sponsors",
        "nav_spon_title": "Nuestros Aliados",
        "nav_spon_desc": "Empresas que hacen posible este evento.",
        "nav_hackatob": "HackaToB",
        "nav_hack_title": "Hackathon ToB",
        "nav_hack_desc": "Participa en el reto de programación.",
        "nav_gallery": "Galería ToB",
        "nav_gallery_title": "Muy pronto...",
        "nav_gallery_desc": "Revive los mejores momentos.",
        "hero_btn_gallery": "Ver Galería",
        "nav_asistir": "Asistir",

        // Hero
        "hero_eyebrow": "Technology on Business",
        "hero_title": "Master <br><span class=\"text-cyan\">The </span>Chaos",
        "hero_status_msg": "System.Weather.Exception: lluvia detectada",
        "hero_new_date": "Nueva fecha por confirmar",
        "hero_time_days": "DÍAS",
        "hero_time_hrs": "HRS",
        "hero_time_min": "MIN",
        "hero_time_seg": "SEG",

        // Solar System
        "planet_1": "Innovación",
        "planet_2": "Networking",
        "planet_3": "Inspiración",
        "planet_4": "Disrupción",
        "planet_5": "Sinergia",
        "planet_6": "Integración",

        // Marquee
        "marquee_text": "15 ANIVERSARIO <span class=\"text-cyan\">✦</span> CUANDO ESCAMPE 2026 <span class=\"text-cyan\">✦</span> MASTER THE CHAOS <span class=\"text-cyan\">✦</span> TECHNOLOGY ON BUSINESS <span class=\"text-cyan\">✦</span> ATI <span class=\"text-cyan\">✦</span> DISRUPCIÓN <span class=\"text-cyan\">✦</span> NETWORKING <span class=\"text-cyan\">✦</span> ",

        // About
        "about_title": "Technology on Business",
        "about_p1": "Technology on Business es un congreso donde estudiantes, profesionales y empresas se reúnen para descubrir las tecnologías, ideas y tendencias que están transformando el futuro.",
        "about_p2": "Con la temática \"Master the Chaos\", la edición 2026 invita a desarrollar las habilidades necesarias para liderar el cambio, innovar y convertir los desafíos en oportunidades.",
        "stat_label_1": "años",
        "stat_desc_1": "impulsando la innovación y el talento tecnológico",
        "stat_label_2": "asistentes",
        "stat_desc_2": "esperados para la edición 2026",
        "stat_label_3": "días",
        "stat_desc_3": "de conferencias, networking y experiencias",
        "stat_label_4": "años TEC",
        "stat_desc_4": "celebrando la innovación y la excelencia académica",
        "bottom_card_title": "Donde las ideas se convierten en oportunidades.",
        "bottom_card_desc": "Dos días para aprender, conectar con líderes de la industria y formar parte de una comunidad que impulsa la innovación y el crecimiento profesional.",

        // Who Attend
        "wa_title": "¿Quiénes asisten?",
        "wa_card1_title": "Estudiantes Universitarios",
        "wa_card1_desc": "Personas que buscan fortalecer sus conocimientos, descubrir nuevas tecnologías y conectar con profesionales de la industria.",
        "wa_card2_title": "Profesionales de TI",
        "wa_card2_desc": "Especialistas en desarrollo de software, infraestructura, datos, inteligencia artificial, ciberseguridad y transformación digital.",
        "wa_card3_title": "Emprendedores e Innovadores",
        "wa_card3_desc": "Fundadores de startups, emprendedores tecnológicos y personas interesadas en convertir ideas en proyectos con impacto.",
        "wa_card4_title": "Empresas y Patrocinadores",
        "wa_card4_desc": "Organizaciones que buscan acercarse al talento universitario, fortalecer su marca y generar oportunidades de colaboración.",
        "wa_card5_title": "Docentes e Investigadores",
        "wa_card5_desc": "Académicos y expertos que impulsan la innovación mediante investigación, transferencia de conocimiento y nuevas metodologías.",
        "wa_card6_title": "Entusiastas de la Tecnología",
        "wa_card6_desc": "Cualquier persona apasionada por la tecnología, la innovación y los negocios que quiera aprender de expertos y ampliar su red.",

        // Phrases
        "phrase_1": "15 Aniversario del TOB",
        "phrase_2": "Mundo BANI",
        "phrase_3": "2 días",
        "phrase_4": "6 bloques",
        "phrase_5": "18 conferencias",
        "phrase_6": 'Estudiantes de <a href="#" class="text-cyan ati-modal-trigger" style="text-decoration:underline;text-underline-offset:4px">ATI</a>',
        "phrase_7": "Congreso de tecnología",
        "phrase_8": "Cuando escampe, 2026",
        "phrase_9": "HackaTob: Nueva fecha por confirmar",

        // Sponsors
        "sponsors_title": "Nuestros Partners",
        "sponsors_text": "Organizaciones que creen en el talento costarricense y se suman para hacer del ToB 2026 una experiencia inolvidable. Su apoyo impulsa a nuestra comunidad y fortalece el futuro de la tecnología en Costa Rica.",
        "main_spon_title": "Nuestros Sponsors",
        "main_spon_text": "Gracias a nuestros sponsors por creer en el poder de la tecnología y la innovación. Su confianza y apoyo hacen posible que el ToB 2026 siga transformando la forma en que conectamos talento, ideas y oportunidades.",

        // Why Attend
        "why_title": "¿Por qué asistir?",
        "why_btn": "Asistir",
        "term_text_1": "> Conectar con +500 apasionados de la tecnología.",
        "term_text_2": "> Aprender de expertos de la industria en charlas exclusivas.",
        "term_text_3": "> Participar en el HackaToB y demostrar tus habilidades.",
        "term_text_4": "> Descubrir oportunidades de networking y crecimiento.",
        "term_text_5": "> Vivir una experiencia inmersiva y única en el TEC.",

        // Presenters
        "presenters_title": "Voces que guían el caos",

        // Speakers
        "speak_label": "Expositores",
        "speak_title": "Las grandes ideas comienzan con una conversación.",
        "speak_desc": "En el ToB tendrás la oportunidad de escuchar a expertos de la industria, descubrir tecnologías emergentes y conectar con personas que comparten tu pasión por la innovación, los negocios y el futuro digital.",
        "speak_btn": "Ver más expositores",
        "mascot_speakers_tag": "AVISO DEL TIBURÓN TOB",
        "mascot_speakers_msg": "Los speakers también se mojaron, nueva fecha en camino.",
        "mascot_prog_tag": "AVISO DEL TIBURÓN TOB",
        "mascot_prog_msg": "El programa está completo, solo le falta la fecha (y que deje de llover).",
        "mascot_hack_tag": "AVISO DEL TIBURÓN TOB",
        "mascot_hack_msg": "HackaTob también sacó el paraguas, nueva fecha muy pronto.",

        // Location
        "loc_label": "Punto de Encuentro",
        "loc_title": "Centro de las Artes, TEC",
        "loc_address": "V34Q+X9W, Centro de las Artes, Tecnológico de Costa Rica,<br>Provincia de Cartago, Cartago",
        "loc_door": "Apertura de puertas",
        "loc_tbd1": "9:00 am",
        "loc_start": "Inicio de evento",
        "loc_tbd2": "9:15 am",
        "loc_maps": "Ver ubicación en Google Maps",

        // Footer
        "footer_desc": "El congreso de tecnología y negocios organizado por estudiantes más grande de Costa Rica.",
        "footer_nav": "Navegación",
        "footer_contact": "Contacto",
        "footer_address": "Centro de las Artes,<br>TEC, Cartago",
        "footer_legal": "Legal",
        "footer_org": "Organizado por estudiantes de la carrera de Administración de Tecnología de Información (ATI) del Instituto Tecnológico de Costa Rica (TEC).🦈",
        "footer_privacy": "Política de Privacidad",
        "footer_terms": "Términos y Condiciones",
        "footer_copy": "© 2026 Technology on Business. Todos los derechos reservados.",

        // Modal
        "modal_text": "Error al cerrar: El ToB 2026 es 🦈inevitable.",
        "modal_btn": "Aceptar",

        // Coordinators
        "coord_label": "Organización",
        "coord_title": "Coordinadores del evento",
        "coord_desc": "Conoce a las personas que están detrás del ToB 2026 y hacen posible este gran evento.",
        "coord_btn_title": "Coordinadores del evento",
        "coord_btn_desc": "Conoce las personas que están detrás del ToB 2026",
        "coord_role_1": "Coordinación General",
        "coord_role_2": "Coordinador de Finanzas & Dev",
        "coord_role_3": "Coordinadora de Mercadeo",
        "coord_role_4": "Coordinador del HackaTob & Dev",
        "coord_role_5": "Coordinadora de Alianzas",
        "coord_role_6": "Asistente Transversal",
        "coord_role_7": "Encargado de Logistica",

        // Presenters (Specific)
        "presenter_1_name": "Anthony Fuentes",
        "presenter_1_role": "Presentador oficial del ToB 2026",
        "presenter_1_bio": "Software Engineer y estudiante de Ingeniería en Computación en el TEC. Fotógrafo y creador de contenido con más de 137 mil seguidores, combinando su pasión por la tecnología con la narrativa visual.",

        "presenter_2_name": "María de la Paz Bloise",
        "presenter_2_role": "Presentadora oficial del ToB 2026",
        "presenter_2_bio": "Coordinadora de Alianzas del TOB y estudiante de Administración de Tecnología de Información en el TEC. Le encanta comunicar, conectar y crear. Este año presenta el panel de mujeres en tecnología. Curiosa y líder, con pasión por conectar personas e ideas.",

        "presenter_3_name": "Julia Vargas Thompson",
        "presenter_3_role": "Asistente Ejecutiva en McKinsey & Company",
        "presenter_3_bio": "Asistente Ejecutiva con experiencia en gestión de agendas, coordinación de proyectos y organización de eventos. Experta en conectar personas, optimizar tiempos y cuidar cada detalle para lograr resultados efectivos.",

        "presenter_coming_name": "Pronto...",
        "presenter_coming_role": "---",
        "presenter_coming_bio": "Más información próximamente.",

        // Speakers Details
        "speaker_01_name": "Pedro Gutiérrez",
        "speaker_01_role": "Avify",
        "speaker_01_bio": "CEO de Avify. Compartirá el camino de construir una startup.",
        "speaker_01_charla": "Empresa de 0 a 1M",

        "speaker_02_name": "Tamara Sancho",
        "speaker_02_role": "P&G",
        "speaker_02_bio": "Transformando el miedo en una herramienta de crecimiento profesional.",
        "speaker_02_charla": "Extraordinary Fears",

        "speaker_03_name": "Pilar Sánchez",
        "speaker_03_role": "Avify",
        "speaker_03_bio": "Líder de la industria compartiendo su visión en resiliencia.",
        "speaker_03_charla": "Panel Mujeres en Tech",

        "speaker_04_name": "Wendy Badilla",
        "speaker_04_role": "Microsoft",
        "speaker_04_bio": "Experta de Microsoft enfocada en empoderamiento femenino en STEM.",
        "speaker_04_charla": "Panel Mujeres en Tech",

        "speaker_05_name": "Aaron Omodeo",
        "speaker_05_role": "Doji Club",
        "speaker_05_bio": "Especialista en finanzas prácticas y toma de decisiones de inversión.",
        "speaker_05_charla": "Finanzas personales en inversiones",

        "speaker_06_name": "Diego Loud",
        "speaker_06_role": "Loud",
        "speaker_06_bio": "Estrategias de mercadeo para conectar con audiencias saturadas.",
        "speaker_06_charla": "Mercadeo en la era digital",

        "speaker_07_name": "María José Artavia",
        "speaker_07_role": "ATI",
        "speaker_07_bio": "Directora dando apertura oficial a TOB-ATI 2026.",
        "speaker_07_charla": "Inauguración",

        "speaker_08_name": "Alek Castillo",
        "speaker_08_role": "Lyfter",
        "speaker_08_bio": "Experta en liderazgo adaptativo en entornos de cambio acelerado.",
        "speaker_08_charla": "Liderazgo en la era de la transformación digital",

        "speaker_09_name": "Alejandro Hidalgo",
        "speaker_09_role": "P&G",
        "speaker_09_bio": "Aplicación de metodologías ágiles para entregar valor más rápido.",
        "speaker_09_charla": "Metodologías ágiles",

        "speaker_10_name": "Gerardo Nájera",
        "speaker_10_role": "Sefisa",
        "speaker_10_bio": "Estrategias de ciberseguridad para proteger información vital.",
        "speaker_10_charla": "Ciberseguridad",

        "speaker_11_name": "Karla Córdoba",
        "speaker_11_role": "Aso Blockchain CR",
        "speaker_11_bio": "Aplicaciones reales de la confianza digital más allá de cripto.",
        "speaker_11_charla": "Blockchain",

        "speaker_12_name": "Ronald Arce",
        "speaker_12_role": "INCAE",
        "speaker_12_bio": "Cómo la IA está redefiniendo los modelos de negocio.",
        "speaker_12_charla": "IA",

        "speaker_13_name": "Muy pronto...",
        "speaker_13_role": "Por definir",
        "speaker_13_bio": "",
        "speaker_13_charla": "...",

        "speaker_14_name": "Muy pronto...",
        "speaker_14_role": "Por definir",
        "speaker_14_bio": "",
        "speaker_14_charla": "...",

        "speaker_15_name": "Muy pronto...",
        "speaker_15_role": "Por definir",
        "speaker_15_bio": "",
        "speaker_15_charla": "...",

        "speaker_16_name": "Muy pronto...",
        "speaker_16_role": "Por definir",
        "speaker_16_bio": "",
        "speaker_16_charla": "...",

        "speaker_17_name": "Muy pronto...",
        "speaker_17_role": "Por definir",
        "speaker_17_bio": "",
        "speaker_17_charla": "...",

        "speaker_18_name": "Rubén Monarca",
        "speaker_18_role": "Actividad Cultural",
        "speaker_18_bio": "",
        "speaker_18_charla": "...",

        "speaker_19_name": "Nestor Morales",
        "speaker_19_role": "Actividad Cultural",
        "speaker_19_bio": "",
        "speaker_19_charla": "...",

        "speaker_20_name": "Pedro Leiva",
        "speaker_20_role": "Actividad Cultural",
        "speaker_20_bio": "",
        "speaker_20_charla": "...",

        "speaker_21_name": "Melody Coto",
        "speaker_21_role": "Actividad Cultural",
        "speaker_21_bio": "",
        "speaker_21_charla": "...",

        // Program Day 1
        "prog_d1_tab": "Día 1 - Por confirmar",
        "prog_d2_tab": "Día 2 - Por confirmar",

        "prog_d1_block1_title": "BLOQUE - INICIO",
        "prog_d1_t1_title": "Inauguración",
        "prog_d1_t1_desc": "Palabras de bienvenida para dar apertura oficial a TOB-ATI 2026, marcando el inicio de dos días dedicados a la innovación, el crecimiento profesional y la conexión con la industria tecnológica.",
        "prog_d1_t1_tag": "Introducción",
        "prog_d1_t2_title": "Acto Cultural: Banda ATI",
        "prog_d1_t2_desc": "Presentación cultural para dar un respiro musical/artístico antes de arrancar con el contenido del día.",
        "prog_d1_t2_tag": "Acto Cultural",
        "prog_d1_t3_title": "Introducción al evento",
        "prog_d1_t3_desc": "Dinámica de bienvenida para romper el hielo entre los asistentes y presentar la mecánica, tracks y objetivos de TOB-ATI 2026.",
        "prog_d1_t3_tag": "Dinámica",

        "prog_d1_block2_title": "BLOQUE - EQUILIBRIO PROPIO",
        "prog_d1_block2_quote": '"You can\'t make change if you can\'t master yourself"',
        "prog_d1_t4_title": "Extraordinary Fears: a quick guide on how to transform fear",
        "prog_d1_t4_desc": "Una guía práctica para identificar el miedo como catalizador en lugar de obstáculo, aprendiendo a gestionarlo para tomar decisiones audaces en la vida y los negocios.",
        "prog_d1_t4_tag": "Charla",
        "prog_d1_t5_title": "Muy pronto",
        "prog_d1_t5_desc": "Estrategias para transmitir ideas con claridad y poder, logrando que el mensaje no solo se escuche, sino que genere impacto y acción en cualquier entorno profesional.",
        "prog_d1_t5_tag": "Taller",
        "prog_d1_t6_title": "Dinámica",
        "prog_d1_t6_desc": "Espacio para retroalimentación vía QR con rifa incluida.",
        "prog_d1_t6_tag": "Rifa",
        "prog_d1_t7_title": "Almuerzo",
        "prog_d1_t7_desc": "Espacio de receso para almorzar y hacer networking.",
        "prog_d1_t7_tag": "Receso",

        "prog_d1_block3_title": "BLOQUE - CRECIMIENTO CONTINUO",
        "prog_d1_block3_quote": '"We are only as strong as we are united, as weak as we are divided"',
        "prog_d1_t8_title": "Empresa de 0 a 1M",
        "prog_d1_t8_desc": "El camino real, sin filtros, de construir una startup desde cero hasta alcanzar su primer millón: los errores, los aciertos y las estrategias de crecimiento acelerado.",
        "prog_d1_t8_tag": "Charla",
        "prog_d1_t9_title": "Muy pronto",
        "prog_d1_t9_desc": "Cómo liderar equipos y organizaciones en medio de la disrupción tecnológica constante, adaptando el estilo de liderazgo a un entorno de cambio acelerado.",
        "prog_d1_t9_tag": "Charla",
        "prog_d1_t10_title": "Acto Cultural",
        "prog_d1_t10_desc": "Presentación cultural para dar dinamismo entre bloques.",
        "prog_d1_t10_tag": "Acto Cultural",
        "prog_d1_t11_title": "Panel: Mujeres en Tech",
        "prog_d1_t11_desc": "Un panel imperdible sobre los retos, perspectivas y el impacto del liderazgo femenino en la industria tecnológica, con voces referentes que están marcando el camino.",
        "prog_d1_t11_tag": "Panel",
        "prog_d1_t12_title": "Dinámica",
        "prog_d1_t12_desc": "Espacio para retroalimentación vía QR con rifa incluida.",
        "prog_d1_t12_tag": "Rifa",
        "prog_d1_t13_title": "Receso",
        "prog_d1_t13_desc": "Pausa corta antes del último bloque del día.",
        "prog_d1_t13_tag": "Receso",

        "prog_d1_block4_title": "BLOQUE - PRODUCTIVIDAD PERSONAL",
        "prog_d1_block4_quote": '"Master your money, master your life"',
        "prog_d1_t14_title": "Finanzas personales en inversiones",
        "prog_d1_t14_desc": "Educación financiera aplicada: cómo tomar el control del dinero, diversificar ingresos y entender los fundamentos de la inversión para construir riqueza a largo plazo.",
        "prog_d1_t14_tag": "Charla",
        "prog_d1_t15_title": "Tips and tricks para una entrevista y crear el CV",
        "prog_d1_t15_desc": "Consejos prácticos y directos para destacar en procesos de selección: desde cómo estructurar un CV efectivo hasta cómo prepararse para una entrevista técnica o de talento.",
        "prog_d1_t15_tag": "Charla",
        "prog_d1_t16_title": "Acto Cultural: Cortometraje",
        "prog_d1_t16_desc": "Proyección de un cortometraje como cierre artístico del bloque.",
        "prog_d1_t16_tag": "Acto Cultural",
        "prog_d1_t17_title": "Muy pronto",
        "prog_d1_t17_desc": "Herramientas y técnicas para comunicar ideas con claridad e impacto, tanto en contextos profesionales como de liderazgo.",
        "prog_d1_t17_tag": "Charla",
        "prog_d1_t18_title": "Cierre y Rifa",
        "prog_d1_t18_desc": "Retroalimentación final del día, cierre oficial y última rifa de la jornada.",
        "prog_d1_t18_tag": "Cierre",

        // Program Day 2
        "prog_d2_block1_title": "BLOQUE - INICIO",
        "prog_d2_t1_title": "Inicio del último día",
        "prog_d2_t1_desc": "Apertura de la segunda y última jornada de TOB-ATI 2026, dando el tono para un día enfocado en optimización, datos y tecnologías disruptivas.",
        "prog_d2_t1_tag": "Introducción",
        "prog_d2_t2_title": "Acto Cultural",
        "prog_d2_t2_desc": "Presentación cultural para dar inicio al día con energía.",
        "prog_d2_t2_tag": "Acto Cultural",
        "prog_d2_t3_title": "Introducción al día",
        "prog_d2_t3_desc": "Formato podcast (o video) para presentar de forma dinámica los temas y objetivos del día: optimización de procesos, cultura de datos y tecnologías disruptivas.",
        "prog_d2_t3_tag": "Podcast",

        "prog_d2_block2_title": "BLOQUE - OPTIMIZACIÓN DE PROCESOS",
        "prog_d2_block2_quote": '"Keep it simple to keep the flow going"',
        "prog_d2_t4_title": "Metodologías ágiles",
        "prog_d2_t4_desc": "Cómo aplicar metodologías ágiles para simplificar procesos, mejorar la colaboración en equipo y entregar valor de forma más rápida y eficiente.",
        "prog_d2_t4_tag": "Charla",
        "prog_d2_t5_title": "Foro: AI Engineer",
        "prog_d2_t5_desc": "Un espacio de storytelling sobre el rol del AI Engineer: cómo es el día a día, qué habilidades se requieren y hacia dónde va esta disciplina en pleno auge de la inteligencia artificial.",
        "prog_d2_t5_tag": "Foro",
        "prog_d2_t6_title": "Dinámica",
        "prog_d2_t6_desc": "Espacio para retroalimentación vía QR con rifa incluida.",
        "prog_d2_t6_tag": "Rifa",
        "prog_d2_t7_title": "Almuerzo",
        "prog_d2_t7_desc": "Espacio de receso para almorzar y hacer networking.",
        "prog_d2_t7_tag": "Receso",

        "prog_d2_block3_title": "BLOQUE - CULTURA DE DATOS",
        "prog_d2_block3_quote": '"Knowledge is power, but data is control"',
        "prog_d2_t8_title": "Ciberseguridad",
        "prog_d2_t8_desc": "Cómo mantener seguros nuestros datos: buenas prácticas, amenazas actuales y estrategias esenciales de ciberseguridad para proteger la información personal y empresarial.",
        "prog_d2_t8_tag": "Charla",
        "prog_d2_t9_title": "Business Intelligence (BI)",
        "prog_d2_t9_desc": "Cómo el uso estratégico de datos impulsa la toma de decisiones empresariales, transformando información en insights accionables para el negocio.",
        "prog_d2_t9_tag": "Charla",
        "prog_d2_t10_title": "Acto Cultural",
        "prog_d2_t10_desc": "Presentación cultural para dar dinamismo entre bloques.",
        "prog_d2_t10_tag": "Acto Cultural",
        "prog_d2_t11_title": "Muy pronto",
        "prog_d2_t11_desc": "Datos en la nube: cómo manejarlos de forma segura y eficiente, y qué modelos de cloud computing están transformando la manera en que las empresas almacenan y procesan información.",
        "prog_d2_t11_tag": "Charla",
        "prog_d2_t12_title": "Dinámica",
        "prog_d2_t12_desc": "Espacio para retroalimentación vía QR con rifa incluida.",
        "prog_d2_t12_tag": "Rifa",
        "prog_d2_t13_title": "Receso",
        "prog_d2_t13_desc": "Pausa corta antes del último bloque del evento.",
        "prog_d2_t13_tag": "Receso",

        "prog_d2_block4_title": "BLOQUE - TECNOLOGÍAS DISRUPTIVAS",
        "prog_d2_block4_quote": '"The rules are being rewritten and we are holding the pen"',
        "prog_d2_t14_title": "Blockchain",
        "prog_d2_t14_desc": "Un vistazo al estado actual del blockchain: aplicaciones reales más allá de las criptomonedas y cómo esta tecnología está reescribiendo las reglas de la confianza digital.",
        "prog_d2_t14_tag": "Charla",
        "prog_d2_t15_title": "Mercadeo en la era digital",
        "prog_d2_t15_desc": "Estrategias de mercadeo digital para conectar con audiencias en un entorno cada vez más saturado de contenido, y cómo destacar con propuestas de valor claras.",
        "prog_d2_t15_tag": "Charla",
        "prog_d2_t16_title": "Acto Cultural",
        "prog_d2_t16_desc": "Presentación cultural para cerrar el ciclo de charlas del día.",
        "prog_d2_t16_tag": "Acto Cultural",
        "prog_d2_t17_title": "IA",
        "prog_d2_t17_desc": "Cómo la inteligencia artificial está redefiniendo los modelos de negocio y por qué adaptarse rápidamente es la única opción viable en el mercado actual.",
        "prog_d2_t17_tag": "Charla",
        "prog_d2_t18_title": "Cierre y Rifa",
        "prog_d2_t18_desc": "Retroalimentación final, cierre oficial del evento y última rifa de TOB-ATI 2026.",
        "prog_d2_t18_tag": "Cierre",

        // ATI Modal
        "ati_lead": "Toda empresa quiere innovar con tecnología. Pocas saben cómo hacerlo bien.",
        "ati_p1": "Ahí es donde entra el Administrador de Tecnología de Información: el profesional que habla el idioma del negocio y el idioma de TI, y logra que ambos se entiendan.",
        "ati_p2": "No es \"el de sistemas\" que solo ejecuta lo que le piden. Tampoco es un gerente que decide sin entender la tecnología. Es el intérprete-negociador que se sienta en el medio: escucha lo que la empresa realmente necesita y traduce eso en soluciones tecnológicas que funcionan de verdad — no solo en teoría.",
        "ati_h1": "¿Por qué esto importa para tu negocio?",
        "ati_p3": "Porque la mayoría de los proyectos de TI fallan no por falta de tecnología, sino por falta de alguien que entienda ambos lados de la mesa.",
        "ati_h2": "Un ATI puede:",
        "ati_li1": "Liderar equipos multidisciplinarios en proyectos de tecnología, de principio a fin",
        "ati_li2": "Evaluar si un proyecto realmente vale la inversión (técnica y económicamente)",
        "ati_li3": "Diseñar soluciones a la medida, no recetas genéricas",
        "ati_li4": "Rediseñar procesos completos usando TI como motor de transformación",
        "ati_li5": "🦈Asesorar a nivel ejecutivo en decisiones estratégicas de tecnología",
        "ati_li6": "Convertir el conocimiento disperso de una organización en una ventaja competitiva real",
        "ati_cta": "Conocer más",

        "prog_hero_eyebrow": "Technology on Business 2026",
        "prog_hero_title": "Programa del <span class=\"text-cyan\">Evento</span>",
        "prog_hero_slogan": "Dos días de conferencias, talleres y networking con los líderes de la industria tecnológica.",
        "prog_date1": "Cuando escampe, 2026",
        "prog_date2": "Cuando escampe, 2026",
        "prog_tab1_day": "Día 1",
        "prog_tab1_date": "Por confirmar",
        "prog_tab2_day": "Día 2",

        // HackaToB Navbar & General
        "hack_nav_back": "&larr; Volver al ToB",
        "hack_nav_back_hack": "&larr; Volver",
        "hack_nav_premios": "Premios",
        "hack_nav_tracks": "Tracks",
        "hack_nav_sedes": "Sedes",
        "hack_nav_agenda": "Agenda",
        "hack_nav_mentores": "Mentores",
        "hack_nav_sponsors": "Sponsors",
        "hack_nav_faq": "FAQ",
        "hack_nav_participar": "Participar",
        "hack_hero_cta": "Quiero participar",

        // HackaToB Metrics
        "hack_metrics_title": "La escala de la primera<br>edición.",
        "hack_stat_1": "Estudiantes esperados",
        "hack_stat_2": "Proyectos",
        "hack_stat_3": "Tracks",
        "hack_stat_4": "Mentores",
        "hack_stat_5": "Jueces Demo Day",
        "hack_prizes_header_eyebrow": "PREMIOS",
        "hack_prizes_header_title": "Trofeos, experiencias y<br>reconocimiento.",
        "hack_tracks_header_eyebrow": "TEMAS",
        "hack_tracks_header_title": "Tres tracks. Tres Sparks.",
        "hack_t1_punch": "Innovación para un futuro sostenible",
        "hack_t1_desc": "Soluciones ambientales relacionadas con sostenibilidad, agricultura, residuos, comunidades y recursos naturales.",
        "hack_t2_punch": "Soluciones para una economía más accesible",
        "hack_t2_desc": "Soluciones financieras, fintech, transparencia, educación e inclusión económica.",
        "hack_t3_punch": "Construye lo que todavía no existe",
        "hack_t3_desc": "Soluciones abiertas con alto potencial de impacto, crecimiento o disrupción.",
        "hack_sedes_header_eyebrow": "DÓNDE OCURRE",
        "hack_sedes_header_title": "EmprendeLab.",
        "hack_sede_role": "Sede Oficial · TEC Cartago",
        "hack_sede_maps": "Cómo llegar",

        // HackaToB Prizes
        "hack_prizes_eyebrow": "PREMIOS OFICIALES · HACKATOB 2026",
        "hack_prizes_title": "Reconocimiento a la <span class=\"text-cyan\">Innovación</span>",
        "hack_prizes_subtitle": "Premios para los 3 mejores proyectos y certificados para todos los participantes.",
        "hack_prize_1_rank": "PRIMER LUGAR",
        "hack_prize_1_amount": "Rainforest Adventures",
        "hack_prize_1_desc": "2 entradas dobles a Rainforest Adventures (canopy o teleférico) + trofeos de campeones.",
        "hack_prize_details": "Ver detalles",
        "hack_prize_1_back_rank": "BENEFICIOS 1° LUGAR",
        "hack_prize_1_back_title": "Gran Ganador ToB",
        "hack_prize_1_li1": "2 Entradas dobles a Rainforest Adventures",
        "hack_prize_1_li2": "Trofeos individuales de Campeones",
        "hack_prize_1_li3": "Exposición destacada de proyecto",
        "hack_prize_1_li4": "Formación y mentoría exclusiva WWT",
        "hack_prize_1_li5": "Magneto + Certificado de participación",
        "hack_prize_back": "Volver al frente",

        "hack_prize_2_rank": "SEGUNDO LUGAR",
        "hack_prize_2_amount": "Premio Plata",
        "hack_prize_2_desc": "Reconocimiento oficial y trofeo conmemorativo para el segundo lugar del Demo Day.",
        "hack_prize_2_back_rank": "BENEFICIOS 2° LUGAR",
        "hack_prize_2_back_title": "Premio Plata",
        "hack_prize_2_li1": "Trofeo conmemorativo Top 2",
        "hack_prize_2_li2": "Exposición destacada de proyecto",
        "hack_prize_2_li3": "Magneto + Certificado de participación",
        "hack_prize_2_li4": "Acceso a workshops y formación",

        "hack_prize_3_rank": "TERCER LUGAR",
        "hack_prize_3_amount": "Premio Bronce",
        "hack_prize_3_desc": "Reconocimiento oficial y trofeo conmemorativo para el tercer lugar del Demo Day.",
        "hack_prize_3_back_rank": "BENEFICIOS 3° LUGAR",
        "hack_prize_3_back_title": "Premio Bronce",
        "hack_prize_3_li1": "Trofeo conmemorativo Top 3",
        "hack_prize_3_li2": "Exposición en la página oficial",
        "hack_prize_3_li3": "Magneto + Certificado de participación",
        "hack_prize_3_li4": "Acceso a workshops y formación",

        "hack_prize_all_rank": "TODOS LOS PARTICIPANTES",
        "hack_prize_all_amount": "Certificado Oficial + Kit",
        "hack_prize_all_desc": "Todos los participantes recibirán certificado digital acreditado y kit conmemorativo del ToB.",
        "hack_prize_all_back_rank": "BENEFICIOS GENERALES",
        "hack_prize_all_back_title": "Comunidad ToB",
        "hack_prize_all_li1": "Certificado digital con valor curricular",
        "hack_prize_all_li2": "Kit de bienvenida del HackaToB",
        "hack_prize_all_li3": "Acceso a todos los workshops",
        "hack_prize_all_li4": "Oportunidades de networking",

        // HackaToB Tracks
        "hack_tracks_eyebrow": "RETOS Y CATEGORÍAS · HACKATOB 2026",
        "hack_tracks_title": "Explora los <span class=\"text-cyan\">Tracks</span>",
        "hack_tracks_subtitle": "Elige el desafío que mejor se adapte a tus habilidades e intereses.",
        "hack_track_1_badge": "TRACK 01",
        "hack_track_1_title": "GreenTrack",
        "hack_track_1_desc": "Tecnología aplicada a la sostenibilidad, optimización energética y reducción de huella ambiental.",
        "hack_track_2_badge": "TRACK 02",
        "hack_track_2_title": "FinTrack",
        "hack_track_2_desc": "Innovación en finanzas digitales, inclusión financiera, ciberseguridad y tecnologías blockchain.",
        "hack_track_3_badge": "TRACK 03",
        "hack_track_3_title": "The Next Big Thing",
        "hack_track_3_desc": "Soluciones disruptivas con Inteligencia Artificial, computación cuántica y tecnologías emergentes.",

        // HackaToB Venues (Sedes)
        "hack_sedes_eyebrow": "ESPACIOS Y UBICACIONES · HACKATOB 2026",
        "hack_sedes_title": "Nuestras <span class=\"text-cyan\">Sedes</span>",
        "hack_sedes_subtitle": "Conoce las sedes oficiales donde se llevará a cabo el HackaToB 2026 en el TEC de Cartago.",
        "hack_sede_1_tag": "Sede Principal · Días 1, 2 y 3",
        "hack_sede_1_title": "EmprendeLab TEC",
        "hack_sede_1_desc": "Espacio de co-working, ideación y laboratorios tecnológicos para el desarrollo y mentorías.",
        "hack_sede_2_tag": "Sede Demo Day · Día 4",
        "hack_sede_2_title": "Auditorio CIC",
        "hack_sede_2_desc": "Escenario principal donde los finalistas presentarán sus proyectos ante el jurado y público general.",

        // HackaToB Agenda Preview & Dedicated
        "hack_agenda_preview_title": "Programa & <span class=\"text-cyan\">Agenda</span>",
        "hack_agenda_preview_subtitle": "Descubre el cronograma completo día por día, workshops, mentorías y entregables cuando escampe, 2026.",
        "hack_agenda_d1_title": "Día 1: PreHackaToB",
        "hack_agenda_d1_desc": "Ideación, retos y formación de equipos en EmprendeLab.",
        "hack_agenda_d2_title": "Día 2: Dev Day I",
        "hack_agenda_d2_desc": "Desarrollo técnico, arquitectura y mentorías especializadas.",
        "hack_agenda_d3_title": "Día 3: Dev Day II",
        "hack_agenda_d3_desc": "Prototipado final, validación y entrega digital 23:59.",
        "hack_agenda_d4_title": "Día 4: Demo Day",
        "hack_agenda_d4_desc": "Pitches ante jurado, evaluación en vivo y premiación.",
        "hack_agenda_cta": "Explorar la Agenda Completa",

        // HackaToB Dedicated Agenda Page
        "hack_agenda_page_title": "Programa del <span class=\"text-cyan\">HackaToB</span>",
        "hack_agenda_page_subtitle": "4 días de aprendizaje, innovación y desarrollo tecnológico en el Instituto Tecnológico de Costa Rica.",

        // HackaToB Tabs
        "hack_tab_d1_badge": "Día 1",
        "hack_tab_d1_num": "Día 1",
        "hack_tab_d1_theme": "PreHackaToB",
        "hack_tab_d2_badge": "Día 2",
        "hack_tab_d2_num": "Día 2",
        "hack_tab_d2_theme": "Dev Day I",
        "hack_tab_d3_badge": "Día 3",
        "hack_tab_d3_num": "Día 3",
        "hack_tab_d3_theme": "Dev Day II",
        "hack_tab_d4_badge": "Día 4",
        "hack_tab_d4_num": "Día 4",
        "hack_tab_d4_theme": "Demo Day",

        // HackaToB Day 1
        "hack_d1_badge": "DÍA 1 · PREHACKATOB",
        "hack_d1_title": "PreHackaToB — Thinking Ahead",
        "hack_d1_subtitle": "PreHackaToB: retos, equipos, ideación y workshops.",
        "hack_d1_date": "Día 1 · Por confirmar",
        "hack_d1_hours": "9:00 a.m. – 7:45 p.m.",
        "hack_d1_obj_label": "Objetivo:",
        "hack_d1_obj_text": "Preparar a los participantes antes de los sprints: contexto del reto, producto y tecnología, integración de equipos, mentoría y herramientas para iniciar el martes.",
        "hack_d1_tag_1": "Inicio",
        "hack_d1_chip_1_1": "Inauguración",
        "hack_d1_chip_1_2": "Qué es HackaToB",
        "hack_d1_chip_1_3": "Acto cultural",
        "hack_d1_chip_1_4": "Propiedad intelectual",
        "hack_d1_tag_2": "Tracks",
        "hack_d1_chip_2_1": "Workshop propuesta de valor",
        "hack_d1_chip_2_2": "GreenTrack / FinTrack / The Next Big Thing",
        "hack_d1_chip_2_3": "Integración de equipo",
        "hack_d1_chip_2_4": "Almuerzo",
        "hack_d1_tag_3": "Tech",
        "hack_d1_chip_3_1": "Blockchain",
        "hack_d1_chip_3_2": "IA",
        "hack_d1_chip_3_3": "Acto cultural",
        "hack_d1_chip_3_4": "Herramienta IA",
        "hack_d1_tag_4": "Mentoría",
        "hack_d1_chip_4_1": "Modalidad UX/UI",
        "hack_d1_chip_4_2": "Herramientas para stack",
        "hack_d1_chip_4_3": "Pitch storytelling",
        "hack_d1_tag_5": "Cierre",
        "hack_d1_chip_5_1": "Cierre del PreHackaToB",
        "hack_d1_chip_5_2": "Networking",
        "hack_d1_res_label": "Resultado:",
        "hack_d1_res_text": "Participantes alineados con retos y tecnologías, equipos integrados y listos para los sprints.",

        // HackaToB Day 2
        "hack_d2_badge": "DÍA 2 · DEV DAY I",
        "hack_d2_title": "Dev Day I · Descubrimiento, diseño y arquitectura",
        "hack_d2_subtitle": "Dev Day I: validación, diseño y desarrollo.",
        "hack_d2_date": "Día 2 · Por confirmar",
        "hack_d2_hours": "10:00 a.m. – 2:00 p.m.",
        "hack_d2_obj_label": "Objetivo:",
        "hack_d2_obj_text": "Transformar el reto en una solución definida y construible: validar problema, acotar alcance, diseñar flujo y preparar arquitectura y backlog.",
        "hack_d2_tag_1": "Stand-up",
        "hack_d2_chip_1_1": "Roles, meta de sprints, bloqueos y criterio de éxito",
        "hack_d2_tag_2": "Sprint 1",
        "hack_d2_chip_2_1": "Descubrir y definir · usuario, problema, propuesta de valor",
        "hack_d2_tag_3": "Checkpoint 1",
        "hack_d2_chip_3_1": "Gate de problema",
        "hack_d2_tag_4": "Pausa",
        "hack_d2_chip_4_1": "Receso",
        "hack_d2_tag_5": "Sprint 2",
        "hack_d2_chip_5_1": "Diseñar y estructurar · flujo, prototipo, stack, backlog",
        "hack_d2_tag_6": "Checkpoint 2 + Cierre",
        "hack_d2_chip_6_1": "Gate de solución",
        "hack_d2_chip_6_2": "Compromiso para el miércoles",
        "hack_d2_res_label": "Resultado:",
        "hack_d2_res_text": "Problema y usuario validados, propuesta de valor, flujo principal, arquitectura y backlog priorizado.",

        // HackaToB Day 3
        "hack_d3_badge": "DÍA 3 · DEV DAY II",
        "hack_d3_title": "Dev Day II · Construcción, validación y entrega",
        "hack_d3_subtitle": "Dev Day II: construcción, mentorías y preparación del pitch.",
        "hack_d3_date": "Día 3 · Por confirmar",
        "hack_d3_hours": "10:00 a.m. – 2:00 p.m. · Entrega digital 11:59 p.m.",
        "hack_d3_obj_label": "Objetivo:",
        "hack_d3_obj_text": "Construir el núcleo demostrable, integrar, probar lo crítico y cerrar con entrega defendible e historia clara para el Demo Day.",
        "hack_d3_tag_1": "Stand-up",
        "hack_d3_chip_1_1": "Freeze de alcance",
        "hack_d3_tag_2": "Sprint 3",
        "hack_d3_chip_2_1": "Construir e integrar el flujo principal",
        "hack_d3_tag_3": "Checkpoint 3",
        "hack_d3_chip_3_1": "Gate funcional",
        "hack_d3_tag_4": "Pausa",
        "hack_d3_chip_4_1": "Receso",
        "hack_d3_tag_5": "Sprint 4",
        "hack_d3_chip_5_1": "Validar y cerrar · README, pitch, demo, video ≤2 min",
        "hack_d3_tag_6": "Checkpoint 4 + Cierre",
        "hack_d3_chip_6_1": "Gate de entrega",
        "hack_d3_chip_6_2": "Plan antes de las 23:59",
        "hack_d3_res_label": "Resultado:",
        "hack_d3_res_text": "Entrega oficial lista. Límite digital: Día 3 · 23:59.",

        // HackaToB Day 4
        "hack_d4_badge": "DÍA 4 · DEMO DAY",
        "hack_d4_title": "Demo Day · Evaluación, premiación y cierre",
        "hack_d4_subtitle": "Demo Day: presentación ante jueces, premiación y cierre.",
        "hack_d4_date": "Día 4 · Por confirmar",
        "hack_d4_hours": "8:00 a.m. – 3:00 p.m. (Llegada 7:30 a.m.)",
        "hack_d4_obj_label": "Objetivo:",
        "hack_d4_obj_text": "Presentar ante el jurado, evaluar con consistencia y cerrar con premiación.",
        "hack_d4_tag_1": "Llegada",
        "hack_d4_chip_1_1": "Acreditación y prueba técnica",
        "hack_d4_tag_2": "Apertura",
        "hack_d4_chip_2_1": "Reglas, tiempos y paneles",
        "hack_d4_tag_3": "Presentaciones",
        "hack_d4_chip_3_1": "Pitches + Q&A jurado",
        "hack_d4_tag_4": "Feria",
        "hack_d4_chip_4_1": "Demostración de stands",
        "hack_d4_tag_5": "Deliberación",
        "hack_d4_chip_5_1": "Calificación y selección",
        "hack_d4_tag_6": "Premiación",
        "hack_d4_chip_6_1": "Top 3 + menciones",
        "hack_d4_chip_6_2": "Clausura oficial",
        "hack_d4_res_label": "Resultado:",
        "hack_d4_res_text": "Resultados formalizados, premiación y cierre de HackaToB 2026.",

        // HackaToB Marquee
        "hack_marquee_track": "HACKATOB <span class=\"text-cyan\">✦</span> FUTURO <span class=\"text-cyan\">✦</span> EMPRENDIMIENTO <span class=\"text-cyan\">✦</span> IMPACTO <span class=\"text-cyan\">✦</span> COMPETENCIA <span class=\"text-cyan\">✦</span> APRENDIZAJE <span class=\"text-cyan\">✦</span> ",

        // HackaToB Mentores & Sponsors
        "hack_mentores_title": "Mentores",
        "hack_partners_title": "Partners HackaToB",
        "hack_platform_label": "Plataforma del hackathon:",
        "hack_allies_title": "Aliados Académicos y Estratégicos",
        "hack_sponsors_title": "Sponsors HackaToB",
        "hack_sponsors_subtitle": "Organizaciones que impulsan el talento y la tecnología en el HackaToB 2026.",

        // HackaToB FAQ
        "hack_faq_title": "Preguntas <span class=\"text-cyan\">Frecuentes</span>",
        "hack_faq_subtitle": "Todo lo que necesitas saber antes de despegar en el HackaToB 2026.",
        "hack_faq_q1": "¿Quién puede participar?",
        "hack_faq_a1": "Estudiantes de todas las carreras, universidades y colegios/escuelas. No necesitas un proyecto terminado ni ser de una carrera tecnológica.",
        "hack_faq_tag1": "PARTICIPACIÓN",
        "hack_faq_q2": "¿Necesito equipo?",
        "hack_faq_a2": "No. Puedes postularte individualmente; habrá integración de equipos en el PreHackaToB. Máximo 4 personas por equipo.",
        "hack_faq_tag2": "EQUIPOS",
        "hack_faq_q3": "¿Necesito saber programar?",
        "hack_faq_a3": "No. Se valoran equipos interdisciplinarios: tecnología, UX/UI, producto, negocio e impacto.",
        "hack_faq_tag3": "PERFIL",
        "hack_faq_q4": "¿Qué es el PreHackaToB?",
        "hack_faq_a4": "Es el Día 1 (lunes 17) en EmprendeLab: retos, equipos, ideación y workshops para llegar listos a los Dev Days.",
        "hack_faq_tag4": "PREHACKATOB",
        "hack_faq_q5": "¿Dónde y a qué horas?",
        "hack_faq_a5": "Lun 17 · 9:00 a.m.–7:45 p.m. EmprendeLab · Mar–Mié 10:00 a.m.–2:00 p.m. EmprendeLab · Jue 20 Demo Day 8:00 a.m.–3:00 p.m. Auditorio CIC. Entrega digital miércoles 23:59.",
        "hack_faq_tag5": "HORARIOS & SEDES",
        "hack_faq_q6": "¿Cuáles son los premios?",
        "hack_faq_a6": "🥇 US$200 + 2 entradas dobles a Rainforest Adventures · 🥈 US$100 · 🥉 US$50. Top 3: trofeos + exposición en la página oficial. Todos: certificado digital de participación.",
        "hack_faq_tag6": "PREMIOS",
        "hack_faq_drag_hint": "Arrastra para descartar",

        // HackaToB Footer
        "hack_footer_desc": "El Hackathon oficial del congreso Technology on Business.",
        "hack_footer_col1": "HackaToB",
        "hack_footer_recursos": "Recursos",
        "hack_footer_col2": "Organización",
        "hack_footer_address": "Centro de las Artes,<br>TEC, Cartago",
        "hack_footer_copy": "&copy; 2026 HackaToB - Technology on Business. Todos los derechos reservados.",
        "prog_tab2_date": "Por confirmar",
        "prog_footer_address": "Área de Tecnología de Información · <strong>ATI TEC</strong><br>Tecnológico de Costa Rica",
        "prog_footer_copy": "© 2026 Technology on Business · ToB. Todos los derechos reservados."
    },
    en: {
        // Navbar & Mobile Menu
        "nav_programa": "Event Schedule",
        "nav_prog_title": "Full Agenda",
        "nav_prog_desc": "Discover all ToB talks and workshops.",
        "nav_speakers": "Speakers",
        "nav_speak_title": "Our Speakers",
        "nav_speak_desc": "Meet the experts leading the event.",
        "nav_sponsors": "Sponsors",
        "nav_spon_title": "Our Partners",
        "nav_spon_desc": "Companies making this event possible.",
        "nav_hackatob": "HackaToB",
        "nav_hack_title": "ToB Hackathon",
        "nav_hack_desc": "Join the programming challenge.",
        "nav_gallery": "ToB Gallery",
        "nav_gallery_title": "Coming soon...",
        "nav_gallery_desc": "Relive the best moments.",
        "hero_btn_gallery": "View Gallery",
        "nav_asistir": "Attend",

        // Hero
        "hero_eyebrow": "Technology on Business",
        "hero_title": "Master <br><span class=\"text-cyan\">The </span>Chaos",
        "hero_status_msg": "System.Weather.Exception: rain detected",
        "hero_new_date": "New date to be confirmed",
        "hero_time_days": "DAYS",
        "hero_time_hrs": "HRS",
        "hero_time_min": "MIN",
        "hero_time_seg": "SEC",

        // Solar System
        "planet_1": "Innovation",
        "planet_2": "Networking",
        "planet_3": "Inspiration",
        "planet_4": "Disruption",
        "planet_5": "Synergy",
        "planet_6": "Integration",

        // Marquee
        "marquee_text": "15TH ANNIVERSARY <span class=\"text-cyan\">✦</span> WHEN THE RAIN CLEARS 2026 <span class=\"text-cyan\">✦</span> MASTER THE CHAOS <span class=\"text-cyan\">✦</span> TECHNOLOGY ON BUSINESS <span class=\"text-cyan\">✦</span> ATI <span class=\"text-cyan\">✦</span> DISRUPTION <span class=\"text-cyan\">✦</span> NETWORKING <span class=\"text-cyan\">✦</span> ",

        // About
        "about_title": "Technology on Business",
        "about_p1": "Technology on Business is a conference where students, professionals, and companies meet to discover the technologies, ideas, and trends transforming the future.",
        "about_p2": "Under the theme \"Master the Chaos\", the 2026 edition invites you to develop the skills needed to lead change, innovate, and turn challenges into opportunities.",
        "stat_label_1": "years",
        "stat_desc_1": "driving innovation and tech talent",
        "stat_label_2": "attendees",
        "stat_desc_2": "expected for the 2026 edition",
        "stat_label_3": "days",
        "stat_desc_3": "of conferences, networking, and experiences",
        "stat_label_4": "years TEC",
        "stat_desc_4": "celebrating innovation and academic excellence",
        "bottom_card_title": "Where ideas turn into opportunities.",
        "bottom_card_desc": "Two days to learn, connect with industry leaders, and become part of a community that drives innovation and professional growth.",

        // Who Attend
        "wa_title": "Who attends?",
        "wa_card1_title": "University Students",
        "wa_card1_desc": "People looking to strengthen their knowledge, discover new technologies, and connect with industry professionals.",
        "wa_card2_title": "IT Professionals",
        "wa_card2_desc": "Specialists in software development, infrastructure, data, artificial intelligence, cybersecurity, and digital transformation.",
        "wa_card3_title": "Entrepreneurs & Innovators",
        "wa_card3_desc": "Startup founders, tech entrepreneurs, and individuals interested in turning ideas into impactful projects.",
        "wa_card4_title": "Companies & Sponsors",
        "wa_card4_desc": "Organizations seeking to connect with university talent, strengthen their brand, and generate collaboration opportunities.",
        "wa_card5_title": "Educators & Researchers",
        "wa_card5_desc": "Academics and experts driving innovation through research, knowledge transfer, and new methodologies.",
        "wa_card6_title": "Tech Enthusiasts",
        "wa_card6_desc": "Anyone passionate about technology, innovation, and business who wants to learn from experts and expand their network.",

        // Phrases
        "phrase_1": "15th Anniversary of TOB",
        "phrase_2": "BANI World",
        "phrase_3": "2 days",
        "phrase_4": "6 blocks",
        "phrase_5": "18 conferences",
        "phrase_6": 'Students of <a href="#" class="text-cyan ati-modal-trigger" style="text-decoration:underline;text-underline-offset:4px">ATI</a>',
        "phrase_7": "Technology Congress",
        "phrase_8": "When the rain clears, 2026",
        "phrase_9": "HackaTob: New date to be confirmed",

        // Sponsors
        "sponsors_title": "Our Partners",
        "sponsors_text": "Organizations that believe in Costa Rican talent and join us to make ToB 2026 an unforgettable experience. Their support boosts our community and strengthens the future of technology in Costa Rica.",
        "main_spon_title": "Our Sponsors",
        "main_spon_text": "Thanks to our sponsors for believing in the power of technology and innovation. Your trust and support make it possible for ToB 2026 to continue transforming the way we connect talent, ideas, and opportunities.",

        // Why Attend
        "why_title": "Why attend?",
        "why_btn": "Attend",
        "term_text_1": "> Connect with +500 tech enthusiasts.",
        "term_text_2": "> Learn from industry experts in exclusive talks.",
        "term_text_3": "> Join HackaToB and showcase your skills.",
        "term_text_4": "> Discover networking and growth opportunities.",
        "term_text_5": "> Live a unique, immersive experience at TEC.",

        // Presenters
        "presenters_title": "Voices guiding the chaos",

        // Speakers
        "speak_label": "Speakers",
        "speak_title": "Great ideas begin with a conversation.",
        "speak_desc": "At ToB you will have the opportunity to listen to industry experts, discover emerging technologies, and connect with people who share your passion for innovation, business, and the digital future.",
        "speak_btn": "See more speakers",
        "mascot_speakers_tag": "TOB SHARK WEATHER NOTICE",
        "mascot_speakers_msg": "Speakers got soaked too, new date on the way.",
        "mascot_prog_tag": "TOB SHARK WEATHER NOTICE",
        "mascot_prog_msg": "The program is complete, it just needs the date (and for the rain to stop).",
        "mascot_hack_tag": "TOB SHARK WEATHER NOTICE",
        "mascot_hack_msg": "HackaTob also pulled out the umbrella, new date very soon.",

        // Presenters (Specific)
        "presenter_1_name": "Anthony Fuentes",
        "presenter_1_role": "Official Host of ToB 2026",
        "presenter_1_bio": "Software Engineer and Computer Engineering student at TEC. Photographer and content creator with over 137 thousand followers, combining his passion for technology with visual storytelling.",

        "presenter_2_name": "María de la Paz Bloise",
        "presenter_2_role": "Official Host of ToB 2026",
        "presenter_2_bio": "TOB Partnerships Coordinator and Information Technology Management student at TEC. She loves communicating, connecting, and creating. This year, she is presenting the panel on women in technology. A curious leader with a passion for connecting people and ideas.",

        "presenter_3_name": "Julia Vargas Thompson",
        "presenter_3_role": "Executive Assistant at McKinsey & Company",
        "presenter_3_bio": "Executive Assistant with experience in calendar management, project coordination, and event organization. Expert at connecting people, optimizing time, and taking care of every detail to achieve effective results.",

        "presenter_coming_name": "Coming Soon...",
        "presenter_coming_role": "---",
        "presenter_coming_bio": "More information coming soon.",

        // Speakers Details
        "speaker_01_name": "Pedro Gutiérrez",
        "speaker_01_role": "Avify",
        "speaker_01_bio": "CEO of Avify. He will share the journey of building a startup.",
        "speaker_01_charla": "Company from 0 to 1M",

        "speaker_02_name": "Tamara Sancho",
        "speaker_02_role": "P&G",
        "speaker_02_bio": "Transforming fear into a tool for professional growth.",
        "speaker_02_charla": "Extraordinary Fears",

        "speaker_03_name": "Pilar Sánchez",
        "speaker_03_role": "Avify",
        "speaker_03_bio": "Industry leader sharing her vision on resilience.",
        "speaker_03_charla": "Women in Tech Panel",

        "speaker_04_name": "Wendy Badilla",
        "speaker_04_role": "Microsoft",
        "speaker_04_bio": "Microsoft expert focused on female empowerment in STEM.",
        "speaker_04_charla": "Women in Tech Panel",

        "speaker_05_name": "Aaron Omodeo",
        "speaker_05_role": "Doji Club",
        "speaker_05_bio": "Specialist in practical finance and investment decision making.",
        "speaker_05_charla": "Personal Finance in Investments",

        "speaker_06_name": "Diego Loud",
        "speaker_06_role": "Loud",
        "speaker_06_bio": "Marketing strategies to connect with saturated audiences.",
        "speaker_06_charla": "Marketing in the digital age",

        "speaker_07_name": "María José Artavia",
        "speaker_07_role": "ATI",
        "speaker_07_bio": "Director giving the official opening for TOB-ATI 2026.",
        "speaker_07_charla": "Inauguration",

        "speaker_08_name": "Alek Castillo",
        "speaker_08_role": "Lyfter",
        "speaker_08_bio": "Expert in adaptive leadership in fast-paced changing environments.",
        "speaker_08_charla": "Leadership in the era of digital transformation",

        "speaker_09_name": "Alejandro Hidalgo",
        "speaker_09_role": "P&G",
        "speaker_09_bio": "Applying agile methodologies to deliver value faster.",
        "speaker_09_charla": "Agile Methodologies",

        "speaker_10_name": "Gerardo Nájera",
        "speaker_10_role": "Sefisa",
        "speaker_10_bio": "Cybersecurity strategies to protect vital information.",
        "speaker_10_charla": "Cybersecurity",

        "speaker_11_name": "Karla Córdoba",
        "speaker_11_role": "Aso Blockchain CR",
        "speaker_11_bio": "Real-world applications of digital trust beyond crypto.",
        "speaker_11_charla": "Blockchain",

        "speaker_12_name": "Ronald Arce",
        "speaker_12_role": "INCAE",
        "speaker_12_bio": "How AI is redefining business models.",
        "speaker_12_charla": "AI",

        "speaker_13_name": "Coming soon...",
        "speaker_13_role": "To be defined",
        "speaker_13_bio": "",
        "speaker_13_charla": "...",

        "speaker_14_name": "Coming soon...",
        "speaker_14_role": "To be defined",
        "speaker_14_bio": "",
        "speaker_14_charla": "...",

        "speaker_15_name": "Coming soon...",
        "speaker_15_role": "To be defined",
        "speaker_15_bio": "",
        "speaker_15_charla": "...",

        "speaker_16_name": "Coming soon...",
        "speaker_16_role": "To be defined",
        "speaker_16_bio": "",
        "speaker_16_charla": "...",

        "speaker_17_name": "Coming soon...",
        "speaker_17_role": "To be defined",
        "speaker_17_bio": "",
        "speaker_17_charla": "...",

        "speaker_18_name": "Rubén Monarca",
        "speaker_18_role": "Cultural Activity",
        "speaker_18_bio": "",
        "speaker_18_charla": "...",

        "speaker_19_name": "Nestor Morales",
        "speaker_19_role": "Cultural Activity",
        "speaker_19_bio": "",
        "speaker_19_charla": "...",

        "speaker_20_name": "Pedro Leiva",
        "speaker_20_role": "Cultural Activity",
        "speaker_20_bio": "",
        "speaker_20_charla": "...",

        "speaker_21_name": "Melody Coto",
        "speaker_21_role": "Cultural Activity",
        "speaker_21_bio": "",
        "speaker_21_charla": "...",

        // Location
        "loc_label": "Meeting Point",
        "loc_title": "Arts Center, TEC",
        "loc_address": "V34Q+X9W, Arts Center, Tecnológico de Costa Rica,<br>Cartago Province, Cartago",
        "loc_door": "Doors open",
        "loc_tbd1": "9:00am",
        "loc_start": "Event starts",
        "loc_tbd2": "9:15 am",
        "loc_maps": "View location on Google Maps",

        // Footer
        "footer_desc": "The largest student-organized technology and business conference in Costa Rica.",
        "footer_nav": "Navigation",
        "footer_contact": "Contact",
        "footer_address": "Arts Center,<br>TEC, Cartago",
        "footer_legal": "Legal",
        "footer_org": "Organized by students of the Information Technology Administration (ATI) program at the Costa Rica Institute of Technology (TEC).🦈",
        "footer_privacy": "Privacy Policy",
        "footer_terms": "Terms and Conditions",
        "footer_copy": "© 2026 Technology on Business. All rights reserved.",

        // Modal
        "modal_text": "Error closing: ToB 2026 is 🦈inevitable.",
        "modal_btn": "Accept",

        // Coordinators
        "coord_label": "Organization",
        "coord_title": "Event Coordinators",
        "coord_desc": "Meet the people behind ToB 2026 who make this great event possible.",
        "coord_btn_title": "Event Coordinators",
        "coord_btn_desc": "Meet the people behind ToB 2026",
        "coord_role_1": "General Coordination",
        "coord_role_2": "Finance & Dev Coordinator",
        "coord_role_3": "Marketing Coordinator",
        "coord_role_4": "HackaTob & Dev Coordinator",
        "coord_role_5": "Alliances Coordinator",
        "coord_role_6": "Cross-cutting Assistant",
        "coord_role_7": "Logistics Manager",

        // Program Day 1
        "prog_d1_tab": "Day 1 - To be confirmed",
        "prog_d2_tab": "Day 2 - To be confirmed",

        "prog_d1_block1_title": "BLOCK - START",
        "prog_d1_t1_title": "Inauguration",
        "prog_d1_t1_desc": "Welcoming words to officially open TOB-ATI 2026, marking the start of two days dedicated to innovation, professional growth, and connection with the tech industry.",
        "prog_d1_t1_tag": "Introduction",
        "prog_d1_t2_title": "Cultural Act: Banda ATI",
        "prog_d1_t2_desc": "Cultural presentation to provide a musical/artistic break before starting with the day's content.",
        "prog_d1_t2_tag": "Cultural Act",
        "prog_d1_t3_title": "Introduction to the event",
        "prog_d1_t3_desc": "Welcome dynamic to break the ice among attendees and present the mechanics, tracks, and objectives of TOB-ATI 2026.",
        "prog_d1_t3_tag": "Dynamic",

        "prog_d1_block2_title": "BLOCK - SELF BALANCE",
        "prog_d1_block2_quote": '"You can\'t make change if you can\'t master yourself"',
        "prog_d1_t4_title": "Extraordinary Fears: a quick guide on how to transform fear",
        "prog_d1_t4_desc": "A practical guide to identify fear as a catalyst rather than an obstacle, learning to manage it to make bold decisions in life and business.",
        "prog_d1_t4_tag": "Talk",
        "prog_d1_t5_title": "Coming soon",
        "prog_d1_t5_desc": "Strategies to convey ideas with clarity and power, ensuring the message is not only heard but generates impact and action in any professional environment.",
        "prog_d1_t5_tag": "Workshop",
        "prog_d1_t6_title": "Dynamic",
        "prog_d1_t6_desc": "Space for feedback via QR with raffle included.",
        "prog_d1_t6_tag": "Raffle",
        "prog_d1_t7_title": "Lunch",
        "prog_d1_t7_desc": "Break space to have lunch and network.",
        "prog_d1_t7_tag": "Break",

        "prog_d1_block3_title": "BLOCK - CONTINUOUS GROWTH",
        "prog_d1_block3_quote": '"We are only as strong as we are united, as weak as we are divided"',
        "prog_d1_t8_title": "Company from 0 to 1M",
        "prog_d1_t8_desc": "The real path, without filters, of building a startup from scratch to reaching its first million: the mistakes, the successes, and accelerated growth strategies.",
        "prog_d1_t8_tag": "Talk",
        "prog_d1_t9_title": "Coming soon",
        "prog_d1_t9_desc": "How to lead teams and organizations in the midst of constant technological disruption, adapting the leadership style to a rapidly changing environment.",
        "prog_d1_t9_tag": "Talk",
        "prog_d1_t10_title": "Cultural Act",
        "prog_d1_t10_desc": "Cultural presentation to provide dynamism between blocks.",
        "prog_d1_t10_tag": "Cultural Act",
        "prog_d1_t11_title": "Panel: Women in Tech",
        "prog_d1_t11_desc": "An unmissable panel on the challenges, perspectives, and impact of female leadership in the tech industry, with leading voices paving the way.",
        "prog_d1_t11_tag": "Panel",
        "prog_d1_t12_title": "Dynamic",
        "prog_d1_t12_desc": "Space for feedback via QR with raffle included.",
        "prog_d1_t12_tag": "Raffle",
        "prog_d1_t13_title": "Break",
        "prog_d1_t13_desc": "Short pause before the last block of the day.",
        "prog_d1_t13_tag": "Break",

        "prog_d1_block4_title": "BLOCK - PERSONAL PRODUCTIVITY",
        "prog_d1_block4_quote": '"Master your money, master your life"',
        "prog_d1_t14_title": "Personal finances in investments",
        "prog_d1_t14_desc": "Applied financial education: how to take control of money, diversify income, and understand the fundamentals of investing to build long-term wealth.",
        "prog_d1_t14_tag": "Talk",
        "prog_d1_t15_title": "Tips and tricks for an interview and creating a CV",
        "prog_d1_t15_desc": "Practical and direct advice to stand out in selection processes: from how to structure an effective CV to how to prepare for a technical or talent interview.",
        "prog_d1_t15_tag": "Talk",
        "prog_d1_t16_title": "Cultural Act: Short Film",
        "prog_d1_t16_desc": "Screening of a short film as an artistic closing of the block.",
        "prog_d1_t16_tag": "Cultural Act",
        "prog_d1_t17_title": "Coming soon",
        "prog_d1_t17_desc": "Tools and techniques to communicate ideas with clarity and impact, both in professional and leadership contexts.",
        "prog_d1_t17_tag": "Talk",
        "prog_d1_t18_title": "Closing and Raffle",
        "prog_d1_t18_desc": "Final feedback, official closing of the day and last raffle of the day.",
        "prog_d1_t18_tag": "Closing",

        // Program Day 2
        "prog_d2_block1_title": "BLOCK - START",
        "prog_d2_t1_title": "Start of the last day",
        "prog_d2_t1_desc": "Opening of the second and last day of TOB-ATI 2026, setting the tone for a day focused on optimization, data, and disruptive technologies.",
        "prog_d2_t1_tag": "Introduction",
        "prog_d2_t2_title": "Cultural Act",
        "prog_d2_t2_desc": "Cultural presentation to start the day with energy.",
        "prog_d2_t2_tag": "Cultural Act",
        "prog_d2_t3_title": "Introduction to the day",
        "prog_d2_t3_desc": "Podcast (or video) format to dynamically present the day's topics and objectives: process optimization, data culture, and disruptive technologies.",
        "prog_d2_t3_tag": "Podcast",

        "prog_d2_block2_title": "BLOCK - PROCESS OPTIMIZATION",
        "prog_d2_block2_quote": '"Keep it simple to keep the flow going"',
        "prog_d2_t4_title": "Agile methodologies",
        "prog_d2_t4_desc": "How to apply agile methodologies to simplify processes, improve team collaboration, and deliver value faster and more efficiently.",
        "prog_d2_t4_tag": "Talk",
        "prog_d2_t5_title": "Forum: AI Engineer",
        "prog_d2_t5_desc": "A storytelling space about the role of the AI Engineer: what the day-to-day is like, what skills are required, and where this discipline is heading in the midst of the artificial intelligence boom.",
        "prog_d2_t5_tag": "Forum",
        "prog_d2_t6_title": "Dynamic",
        "prog_d2_t6_desc": "Space for feedback via QR with raffle included.",
        "prog_d2_t6_tag": "Raffle",
        "prog_d2_t7_title": "Lunch",
        "prog_d2_t7_desc": "Break space to have lunch and network.",
        "prog_d2_t7_tag": "Break",

        "prog_d2_block3_title": "BLOCK - DATA CULTURE",
        "prog_d2_block3_quote": '"Knowledge is power, but data is control"',
        "prog_d2_t8_title": "Cybersecurity",
        "prog_d2_t8_desc": "How to keep our data safe: best practices, current threats, and essential cybersecurity strategies to protect personal and business information.",
        "prog_d2_t8_tag": "Talk",
        "prog_d2_t9_title": "Business Intelligence (BI)",
        "prog_d2_t9_desc": "How the strategic use of data drives business decision-making, transforming information into actionable insights for the business.",
        "prog_d2_t9_tag": "Talk",
        "prog_d2_t10_title": "Cultural Act",
        "prog_d2_t10_desc": "Cultural presentation to provide dynamism between blocks.",
        "prog_d2_t10_tag": "Cultural Act",
        "prog_d2_t11_title": "Coming soon",
        "prog_d2_t11_desc": "Data in the cloud: how to manage it securely and efficiently, and what cloud computing models are transforming the way companies store and process information.",
        "prog_d2_t11_tag": "Talk",
        "prog_d2_t12_title": "Dynamic",
        "prog_d2_t12_desc": "Space for feedback via QR with raffle included.",
        "prog_d2_t12_tag": "Raffle",
        "prog_d2_t13_title": "Break",
        "prog_d2_t13_desc": "Short pause before the last block of the event.",
        "prog_d2_t13_tag": "Break",

        "prog_d2_block4_title": "BLOCK - DISRUPTIVE TECHNOLOGIES",
        "prog_d2_block4_quote": '"The rules are being rewritten and we are holding the pen"',
        "prog_d2_t14_title": "Blockchain",
        "prog_d2_t14_desc": "A look at the current state of blockchain: real applications beyond cryptocurrencies and how this technology is rewriting the rules of digital trust.",
        "prog_d2_t14_tag": "Talk",
        "prog_d2_t15_title": "Marketing in the digital era",
        "prog_d2_t15_desc": "Digital marketing strategies to connect with audiences in an increasingly content-saturated environment, and how to stand out with clear value propositions.",
        "prog_d2_t15_tag": "Talk",
        "prog_d2_t16_title": "Cultural Act",
        "prog_d2_t16_desc": "Cultural presentation to close the day's cycle of talks.",
        "prog_d2_t16_tag": "Cultural Act",
        "prog_d2_t17_title": "AI",
        "prog_d2_t17_desc": "How artificial intelligence is redefining business models and why adapting quickly is the only viable option in today's market.",
        "prog_d2_t17_tag": "Talk",
        "prog_d2_t18_title": "Closing and Raffle",
        "prog_d2_t18_desc": "Final feedback, official closing of the event, and the last raffle of TOB-ATI 2026.",
        "prog_d2_t18_tag": "Closing",

        // ATI Modal
        "ati_lead": "Every company wants to innovate with technology. Few know how to do it right.",
        "ati_p1": "That's where the Information Technology Administrator comes in: the professional who speaks both the language of business and IT, and makes them understand each other.",
        "ati_p2": "They are not just the \"IT guy\" who executes requests. Nor a manager who decides without understanding technology. They are the interpreter-negotiator in the middle: listening to what the company truly needs and translating that into technological solutions that actually work — not just in theory.",
        "ati_h1": "Why does this matter for your business?",
        "ati_p3": "Because most IT projects fail not due to a lack of technology, but due to the absence of someone who understands both sides of the table.",
        "ati_h2": "An ATI can:",
        "ati_li1": "Lead multidisciplinary teams in technology projects, from start to finish",
        "ati_li2": "Evaluate whether a project is truly worth the investment (technologically and economically)",
        "ati_li3": "Design tailor-made solutions, not generic recipes",
        "ati_li4": "Redesign entire processes using IT as a transformation engine",
        "ati_li5": "🦈Advise at the executive level on strategic technology decisions",
        "ati_li6": "Turn an organization's scattered knowledge into a real competitive advantage",
        "ati_cta": "Learn more",

        "prog_hero_eyebrow": "Technology on Business 2026",
        "prog_hero_title": "Event <span class=\"text-cyan\">Program</span>",
        "prog_hero_slogan": "Two days of conferences, workshops, and networking with technology industry leaders.",
        "prog_date1": "When the rain clears, 2026",
        "prog_date2": "When the rain clears, 2026",
        "prog_tab1_day": "Day 1",
        "prog_tab1_date": "To be confirmed",
        "prog_tab2_day": "Day 2",
        "prog_tab2_date": "To be confirmed",
        "prog_footer_address": "Information Technology Area · <strong>ATI TEC</strong><br>Costa Rica Institute of Technology",
        "prog_footer_copy": "© 2026 Technology on Business · ToB. All rights reserved.",

        // HackaToB Navbar & General
        "hack_nav_back": "&larr; Back to ToB",
        "hack_nav_back_hack": "&larr; Back",
        "hack_nav_premios": "Prizes",
        "hack_nav_tracks": "Tracks",
        "hack_nav_sedes": "Venues",
        "hack_nav_agenda": "Schedule",
        "hack_nav_mentores": "Mentors",
        "hack_nav_sponsors": "Sponsors",
        "hack_nav_faq": "FAQ",
        "hack_nav_participar": "Participate",
        "hack_hero_cta": "Join Hackathon",

        // HackaToB Metrics
        "hack_metrics_title": "The scale of the first<br>edition.",
        "hack_stat_1": "Expected students",
        "hack_stat_2": "Projects",
        "hack_stat_3": "Tracks",
        "hack_stat_4": "Mentors",
        "hack_stat_5": "Demo Day Judges",
        "hack_prizes_header_eyebrow": "PRIZES",
        "hack_prizes_header_title": "Trophies, experiences, and<br>recognition.",
        "hack_tracks_header_eyebrow": "THEMES",
        "hack_tracks_header_title": "Three tracks. Three Sparks.",
        "hack_t1_punch": "Innovation for a sustainable future",
        "hack_t1_desc": "Environmental solutions related to sustainability, agriculture, waste, communities, and natural resources.",
        "hack_t2_punch": "Solutions for a more accessible economy",
        "hack_t2_desc": "Financial solutions, fintech, transparency, education, and economic inclusion.",
        "hack_t3_punch": "Build what doesn't exist yet",
        "hack_t3_desc": "Open solutions with high potential for impact, growth, or disruption.",
        "hack_sedes_header_eyebrow": "WHERE IT HAPPENS",
        "hack_sedes_header_title": "EmprendeLab.",
        "hack_sede_role": "Official Venue · TEC Cartago",
        "hack_sede_maps": "Get Directions",

        // HackaToB Prizes
        "hack_prizes_eyebrow": "OFFICIAL PRIZES · HACKATOB 2026",
        "hack_prizes_title": "Recognition of <span class=\"text-cyan\">Innovation</span>",
        "hack_prizes_subtitle": "Prizes for the top 3 projects and certificates for all participants.",
        "hack_prize_1_rank": "FIRST PLACE",
        "hack_prize_1_amount": "Rainforest Adventures",
        "hack_prize_1_desc": "2 double passes to Rainforest Adventures (zipline or aerial tram) + Champion trophies.",
        "hack_prize_details": "View details",
        "hack_prize_1_back_rank": "1ST PLACE BENEFITS",
        "hack_prize_1_back_title": "Grand Winner ToB",
        "hack_prize_1_li1": "2 Double passes to Rainforest Adventures",
        "hack_prize_1_li2": "Individual Champion trophies",
        "hack_prize_1_li3": "Featured project showcase",
        "hack_prize_1_li4": "Exclusive WWT training and mentorship",
        "hack_prize_1_li5": "Magnet + Certificate of participation",
        "hack_prize_back": "Back to front",

        "hack_prize_2_rank": "SECOND PLACE",
        "hack_prize_2_amount": "Silver Prize",
        "hack_prize_2_desc": "Official recognition and commemorative trophy for second place at Demo Day.",
        "hack_prize_2_back_rank": "2ND PLACE BENEFITS",
        "hack_prize_2_back_title": "Silver Prize",
        "hack_prize_2_li1": "Top 2 commemorative trophy",
        "hack_prize_2_li2": "Featured project showcase",
        "hack_prize_2_li3": "Magnet + Certificate of participation",
        "hack_prize_2_li4": "Access to workshops and training",

        "hack_prize_3_rank": "THIRD PLACE",
        "hack_prize_3_amount": "Bronze Prize",
        "hack_prize_3_desc": "Official recognition and commemorative trophy for third place at Demo Day.",
        "hack_prize_3_back_rank": "3RD PLACE BENEFITS",
        "hack_prize_3_back_title": "Bronze Prize",
        "hack_prize_3_li1": "Top 3 commemorative trophy",
        "hack_prize_3_li2": "Showcase on official website",
        "hack_prize_3_li3": "Magnet + Certificate of participation",
        "hack_prize_3_li4": "Access to workshops and training",

        "hack_prize_all_rank": "ALL PARTICIPANTS",
        "hack_prize_all_amount": "Official Certificate + Kit",
        "hack_prize_all_desc": "All participants will receive an accredited digital certificate and commemorative ToB kit.",
        "hack_prize_all_back_rank": "GENERAL BENEFITS",
        "hack_prize_all_back_title": "ToB Community",
        "hack_prize_all_li1": "Digital certificate with curricular value",
        "hack_prize_all_li2": "HackaToB welcome kit",
        "hack_prize_all_li3": "Access to all workshops",
        "hack_prize_all_li4": "Networking opportunities",

        // HackaToB Tracks
        "hack_tracks_eyebrow": "CHALLENGES & CATEGORIES · HACKATOB 2026",
        "hack_tracks_title": "Explore the <span class=\"text-cyan\">Tracks</span>",
        "hack_tracks_subtitle": "Choose the challenge that best fits your skills and interests.",
        "hack_track_1_badge": "TRACK 01",
        "hack_track_1_title": "GreenTrack",
        "hack_track_1_desc": "Technology applied to sustainability, energy optimization, and environmental footprint reduction.",
        "hack_track_2_badge": "TRACK 02",
        "hack_track_2_title": "FinTrack",
        "hack_track_2_desc": "Innovation in digital finance, financial inclusion, cybersecurity, and blockchain technologies.",
        "hack_track_3_badge": "TRACK 03",
        "hack_track_3_title": "The Next Big Thing",
        "hack_track_3_desc": "Disruptive solutions with Artificial Intelligence, quantum computing, and emerging tech.",

        // HackaToB Venues (Sedes)
        "hack_sedes_eyebrow": "SPACES & LOCATIONS · HACKATOB 2026",
        "hack_sedes_title": "Our <span class=\"text-cyan\">Venues</span>",
        "hack_sedes_subtitle": "Discover the official venues hosting HackaToB 2026 at TEC Cartago.",
        "hack_sede_1_tag": "Main Venue · Days 1, 2 & 3",
        "hack_sede_1_title": "EmprendeLab TEC",
        "hack_sede_1_desc": "Co-working space, ideation labs, and tech infrastructure for development and mentoring.",
        "hack_sede_2_tag": "Demo Day Venue · Day 4",
        "hack_sede_2_title": "CIC Auditorium",
        "hack_sede_2_desc": "Main stage where finalists will pitch their projects to judges and attendees.",

        // HackaToB Agenda Preview & Dedicated
        "hack_agenda_preview_title": "Program & <span class=\"text-cyan\">Schedule</span>",
        "hack_agenda_preview_subtitle": "Explore the full day-by-day schedule, workshops, mentorship sessions, and deliverables when the rain clears, 2026.",
        "hack_agenda_d1_title": "Day 1: PreHackaToB",
        "hack_agenda_d1_desc": "Ideation, challenges, and team formation at EmprendeLab.",
        "hack_agenda_d2_title": "Day 2: Dev Day I",
        "hack_agenda_d2_desc": "Technical development, architecture, and specialized mentorship.",
        "hack_agenda_d3_title": "Day 3: Dev Day II",
        "hack_agenda_d3_desc": "Final prototyping, validation, and digital submission by 11:59 PM.",
        "hack_agenda_d4_title": "Day 4: Demo Day",
        "hack_agenda_d4_desc": "Live pitches to judges, real-time evaluation, and awards ceremony.",
        "hack_agenda_cta": "Explore Full Schedule",

        // HackaToB Dedicated Agenda Page
        "hack_agenda_page_title": "HackaToB <span class=\"text-cyan\">Program</span>",
        "hack_agenda_page_subtitle": "4 days of learning, innovation, and tech development at Costa Rica Institute of Technology.",

        // HackaToB Tabs
        "hack_tab_d1_badge": "Day 1",
        "hack_tab_d1_num": "Day 1",
        "hack_tab_d1_theme": "PreHackaToB",
        "hack_tab_d2_badge": "Day 2",
        "hack_tab_d2_num": "Day 2",
        "hack_tab_d2_theme": "Dev Day I",
        "hack_tab_d3_badge": "Day 3",
        "hack_tab_d3_num": "Day 3",
        "hack_tab_d3_theme": "Dev Day II",
        "hack_tab_d4_badge": "Day 4",
        "hack_tab_d4_num": "Day 4",
        "hack_tab_d4_theme": "Demo Day",

        // HackaToB Day 1
        "hack_d1_badge": "DAY 1 · PREHACKATOB",
        "hack_d1_title": "PreHackaToB — Thinking Ahead",
        "hack_d1_subtitle": "PreHackaToB: challenges, teams, ideation, and workshops.",
        "hack_d1_date": "Day 1 · To be confirmed",
        "hack_d1_hours": "9:00 AM – 7:45 PM",
        "hack_d1_obj_label": "Objective:",
        "hack_d1_obj_text": "Prepare participants before the sprints: challenge context, product & technology, team integration, mentoring, and tools to kick off Tuesday.",
        "hack_d1_tag_1": "Kickoff",
        "hack_d1_chip_1_1": "Opening ceremony",
        "hack_d1_chip_1_2": "What is HackaToB",
        "hack_d1_chip_1_3": "Cultural presentation",
        "hack_d1_chip_1_4": "Intellectual property",
        "hack_d1_tag_2": "Tracks",
        "hack_d1_chip_2_1": "Value proposition workshop",
        "hack_d1_chip_2_2": "GreenTrack / FinTrack / The Next Big Thing",
        "hack_d1_chip_2_3": "Team integration",
        "hack_d1_chip_2_4": "Lunch",
        "hack_d1_tag_3": "Tech",
        "hack_d1_chip_3_1": "Blockchain",
        "hack_d1_chip_3_2": "AI",
        "hack_d1_chip_3_3": "Cultural presentation",
        "hack_d1_chip_3_4": "AI Tools",
        "hack_d1_tag_4": "Mentoring",
        "hack_d1_chip_4_1": "UX/UI track",
        "hack_d1_chip_4_2": "Stack tools",
        "hack_d1_chip_4_3": "Pitch storytelling",
        "hack_d1_tag_5": "Closing",
        "hack_d1_chip_5_1": "PreHackaToB Closing",
        "hack_d1_chip_5_2": "Networking",
        "hack_d1_res_label": "Outcome:",
        "hack_d1_res_text": "Participants aligned with challenges and technologies, teams integrated and ready for sprints.",

        // HackaToB Day 2
        "hack_d2_badge": "DAY 2 · DEV DAY I",
        "hack_d2_title": "Dev Day I · Discovery, design & architecture",
        "hack_d2_subtitle": "Dev Day I: validation, design, and development.",
        "hack_d2_date": "Day 2 · To be confirmed",
        "hack_d2_hours": "10:00 AM – 2:00 PM",
        "hack_d2_obj_label": "Objective:",
        "hack_d2_obj_text": "Transform the challenge into a defined, buildable solution: validate the problem, narrow scope, design user flow, and prepare architecture and backlog.",
        "hack_d2_tag_1": "Stand-up",
        "hack_d2_chip_1_1": "Roles, sprint goals, blockers & success criteria",
        "hack_d2_tag_2": "Sprint 1",
        "hack_d2_chip_2_1": "Discover & define · user, problem, value proposition",
        "hack_d2_tag_3": "Checkpoint 1",
        "hack_d2_chip_3_1": "Problem gate",
        "hack_d2_tag_4": "Break",
        "hack_d2_chip_4_1": "Break",
        "hack_d2_tag_5": "Sprint 2",
        "hack_d2_chip_5_1": "Design & structure · flow, prototype, stack, backlog",
        "hack_d2_tag_6": "Checkpoint 2 + Wrap-up",
        "hack_d2_chip_6_1": "Solution gate",
        "hack_d2_chip_6_2": "Commitment for Wednesday",
        "hack_d2_res_label": "Outcome:",
        "hack_d2_res_text": "Problem and user validated, value proposition, main flow, architecture, and prioritized backlog.",

        // HackaToB Day 3
        "hack_d3_badge": "DAY 3 · DEV DAY II",
        "hack_d3_title": "Dev Day II · Construction, validation & delivery",
        "hack_d3_subtitle": "Dev Day II: construction, mentoring, and pitch prep.",
        "hack_d3_date": "Day 3 · To be confirmed",
        "hack_d3_hours": "10:00 AM – 2:00 PM · Digital submission 11:59 PM",
        "hack_d3_obj_label": "Objective:",
        "hack_d3_obj_text": "Build the demonstrable core, integrate, test critical features, and close with a defensible delivery and clear story for Demo Day.",
        "hack_d3_tag_1": "Stand-up",
        "hack_d3_chip_1_1": "Scope freeze",
        "hack_d3_tag_2": "Sprint 3",
        "hack_d3_chip_2_1": "Build & integrate core user flow",
        "hack_d3_tag_3": "Checkpoint 3",
        "hack_d3_chip_3_1": "Functional gate",
        "hack_d3_tag_4": "Break",
        "hack_d3_chip_4_1": "Break",
        "hack_d3_tag_5": "Sprint 4",
        "hack_d3_chip_5_1": "Validate & finish · README, pitch, demo, video ≤2 min",
        "hack_d3_tag_6": "Checkpoint 4 + Wrap-up",
        "hack_d3_chip_6_1": "Delivery gate",
        "hack_d3_chip_6_2": "Action plan before 11:59 PM",
        "hack_d3_res_label": "Outcome:",
        "hack_d3_res_text": "Official submission ready. Digital deadline: Day 3 · 11:59 PM.",

        // HackaToB Day 4
        "hack_d4_badge": "DAY 4 · DEMO DAY",
        "hack_d4_title": "Demo Day · Evaluation, awards & closing",
        "hack_d4_subtitle": "Demo Day: pitch to judges, awards ceremony, and closing.",
        "hack_d4_date": "Day 4 · To be confirmed",
        "hack_d4_hours": "8:00 AM – 3:00 PM (Arrival 7:30 AM)",
        "hack_d4_obj_label": "Objective:",
        "hack_d4_obj_text": "Present before the jury, evaluate consistently, and conclude with the awards ceremony.",
        "hack_d4_tag_1": "Arrival",
        "hack_d4_chip_1_1": "Check-in & technical check",
        "hack_d4_tag_2": "Opening",
        "hack_d4_chip_2_1": "Rules, timing & judge panels",
        "hack_d4_tag_3": "Presentations",
        "hack_d4_chip_3_1": "Video ≤2 min + 5 min pitch + Q&A ≤10 min",
        "hack_d4_tag_4": "Break",
        "hack_d4_chip_4_1": "Contingency / break: remaining projects or intermission",
        "hack_d4_tag_5": "Deliberation",
        "hack_d4_chip_5_1": "Jury evaluation & score validation",
        "hack_d4_tag_6": "🏆 Awards Ceremony",
        "hack_d4_chip_6_1": "Awards, certificates & official closing",
        "hack_d4_res_label": "Outcome:",
        "hack_d4_res_text": "Results finalized, awards ceremony, and HackaToB 2026 closing.",

        // HackaToB Marquee
        "hack_marquee_track": "HACKATOB <span class=\"text-cyan\">✦</span> FUTURE <span class=\"text-cyan\">✦</span> ENTREPRENEURSHIP <span class=\"text-cyan\">✦</span> IMPACT <span class=\"text-cyan\">✦</span> COMPETITION <span class=\"text-cyan\">✦</span> LEARNING <span class=\"text-cyan\">✦</span> ",

        // HackaToB Mentores & Sponsors
        "hack_mentores_title": "Mentors",
        "hack_partners_title": "HackaToB Partners",
        "hack_platform_label": "Hackathon Platform:",
        "hack_allies_title": "Academic & Strategic Allies",
        "hack_sponsors_title": "HackaToB Sponsors",
        "hack_sponsors_subtitle": "Organizations powering talent and technology at HackaToB 2026.",

        // HackaToB FAQ
        "hack_faq_title": "Frequently Asked <span class=\"text-cyan\">Questions</span>",
        "hack_faq_subtitle": "Everything you need to know before taking off at HackaToB 2026.",
        "hack_faq_q1": "Who can participate?",
        "hack_faq_a1": "Students of all majors, universities, and high schools. You do not need a finished project or a tech background.",
        "hack_faq_tag1": "PARTICIPATION",
        "hack_faq_q2": "Do I need a team?",
        "hack_faq_a2": "No. You can apply individually; team formation takes place at PreHackaToB. Maximum 4 people per team.",
        "hack_faq_tag2": "TEAMS",
        "hack_faq_q3": "Do I need coding experience?",
        "hack_faq_a3": "No. Interdisciplinary teams are highly valued: technology, UX/UI, product, business, and impact.",
        "hack_faq_tag3": "PROFILE",
        "hack_faq_q4": "What is PreHackaToB?",
        "hack_faq_a4": "It is Day 1 (Monday 17) at EmprendeLab: challenges, teams, ideation, and workshops to get ready for Dev Days.",
        "hack_faq_tag4": "PREHACKATOB",
        "hack_faq_q5": "Where and when?",
        "hack_faq_a5": "Mon 17 · 9:00 a.m.–7:45 p.m. EmprendeLab · Tue–Wed 10:00 a.m.–2:00 p.m. EmprendeLab · Thu 20 Demo Day 8:00 a.m.–3:00 p.m. CIC Auditorium. Digital submission Wednesday 11:59 p.m.",
        "hack_faq_tag5": "SCHEDULE & VENUES",
        "hack_faq_q6": "What are the prizes?",
        "hack_faq_a6": "🥇 US$200 + 2 double passes to Rainforest Adventures · 🥈 US$100 · 🥉 US$50. Top 3: trophies + official website showcase. All: digital certificate of participation.",
        "hack_faq_tag6": "PRIZES",
        "hack_faq_drag_hint": "Drag to dismiss",

        // HackaToB Footer
        "hack_footer_desc": "The official Hackathon of the Technology on Business conference.",
        "hack_footer_col1": "HackaToB",
        "hack_footer_recursos": "Resources",
        "hack_footer_col2": "Organization",
        "hack_footer_address": "Arts Center,<br>TEC, Cartago",
        "hack_footer_copy": "&copy; 2026 HackaToB - Technology on Business. All rights reserved."
    }
};

// LOGICA DE TRADUCCION
function applyTranslations(lang) {
    const elements = document.querySelectorAll('[data-i18n]');
    elements.forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            el.innerHTML = translations[lang][key];
        }
    });

    // Update active class on language selectors
    document.querySelectorAll('.lang-selector').forEach(selector => {
        const spans = selector.querySelectorAll('.lang-text');
        const slider = selector.querySelector('.lang-slider');

        spans.forEach(span => span.classList.remove('active'));

        if (lang === 'en') {
            if (spans.length > 1) spans[1].classList.add('active'); // EN
            if (slider) slider.style.transform = 'translateX(100%)';
            selector.setAttribute('data-lang', 'EN');
        } else {
            if (spans.length > 0) spans[0].classList.add('active'); // ES
            if (slider) slider.style.transform = 'translateX(0)';
            selector.setAttribute('data-lang', 'ES');
        }
    });

    // Also update footer language selectors (which are just simple spans/a)
    document.querySelectorAll('.footer-lang-selector').forEach(selector => {
        selector.innerHTML = lang === 'es'
            ? `<span class="lang-active">ES</span> | <a href="#" class="lang-switch" data-target="en">EN</a>`
            : `<a href="#" class="lang-switch" data-target="es">ES</a> | <span class="lang-active">EN</span>`;

        // Re-attach listeners for footer newly generated links
        const newLinks = selector.querySelectorAll('.lang-switch');
        newLinks.forEach(link => {
            link.addEventListener('click', (e) => {
                e.preventDefault();
                setLanguage(e.target.getAttribute('data-target'));
            });
        });
    });

    document.documentElement.lang = lang;
}

function setLanguage(lang) {
    localStorage.setItem('tob_lang', lang);
    applyTranslations(lang);

    // Trigger a custom event in case other scripts need to know (like the terminal text)
    window.dispatchEvent(new CustomEvent('languageChanged', { detail: { lang } }));
}

// Initial setup
document.addEventListener('DOMContentLoaded', () => {
    // Get saved language or default to 'es'
    const savedLang = localStorage.getItem('tob_lang') || 'es';

    // Add click events to main toggles (navbar and mobile menu)
    const langToggles = document.querySelectorAll('.lang-selector');
    langToggles.forEach(toggle => {
        // Toggle on click anywhere in the selector
        toggle.addEventListener('click', () => {
            const currentLang = localStorage.getItem('tob_lang') || 'es';
            const newLang = currentLang === 'es' ? 'en' : 'es';
            setLanguage(newLang);
        });
    });

    // Apply translations
    setLanguage(savedLang);
});
